version: "3.8"

services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_pwd
  backend:
    build: ./backend
    image: django-postgres-backend:1.0.0
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - ./backend/:/home/app/backend/
    ports:
      - "7200:7000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres-data:
