version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=app_pwd
  backend:
    build: ./backend
    image: docker.pkg.github.com/ajithpmohan/django-postgresql-boilerplate/backend-dev:1.0
    command: python manage.py runserver 0.0.0.0:7000
    volumes:
      - ./backend/:/usr/src/app/backend/
    ports:
      - "7100:7000"
    env_file:
      - ./backend/.env.dev
    depends_on:
      - db
    stdin_open: true
    tty: true

volumes:
  postgres-data:
