version: "3.8"

services:
  pre-commit:
    build:
      context: .
      dockerfile: Dockerfile.pre-commit
    image: django-postgres-pre-commit
    command: bash -c "pre-commit autoupdate && pre-commit run --all-files"
    volumes:
      - .:/home/app
